name: No ordinary Life
favicon: null
layout_spectrum: 0.8214867869392037
typography_spectrum: 0.9826037180610001
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.09103360679000616
  lightness: 0.45825203182175756
  saturation: 0.663318153237924
  rhythmicContrast: 0.8794613941572607
purpose: []
